cilium/little-vm-helper

- README.md
- pkg/images/conf.go
- pkg/images/step_create_image.go
Apparently, the 8G default is not enough when running Kind + Cilium +
"cilium connectivity test".
> images: Allow to specify img size

- cmd/lvh/main.go
- cmd/lvh/runner/conf.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
- scripts/example.sh
This commit add the `lvh run` command, which is a generalized version
of the Tetragon runner. It is essentially a small wrapper around qemu
to aid in setting the correct attributes to make it run. It modifies the
base image in its current iteration to add test scripts and systemd
services.
HOWTO run it:
mkdir images
docker run -v $(pwd)/images:/mnt/images \
quay.io/lvh-images/root-images:latest \
cp /data/images/kind.qcow2.zst /mnt/images
cd images
zstd -d kind.qcow2.zst && cd ..
go run ./cmd/lvh run --image images/cilium.qcow2 \
--mount ~/sandbox/gopath/src/github.com/cilium/ \
--daemonize -p 2222:22
ssh -p 2222 -o "StrictHostKeyChecking=no" root@localhost
> runner: Added VM runner

- Makefile
Then the executable can be extracted from the Docker LVH image.
Signed-off-by: Martynas Pumputis <m@lambda.lt>
> make: Statically link lvh

- cmd/lvh/runner/conf.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
This commit adds a new flag to change CPU kind (the -cpu flag in qemu). This way we can pass different types as needed, for example "host" to get a slight performance boost. Default to kvm64 as it provides the strongest compatibility guarantees and mirrors the old behaviour.
Signed-off-by: William Findlay <will@isovalent.com>
> subcommands/run: add a flag to change cpu kind

- cmd/lvh/runner/conf.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
Add an option to enable TCP-based QEMU monitor port. With this port, we can easily operate on the QEMU system. For example, we can kill VM process by `echo q | nc localhost <monitor port>`. Currently, this is the only usecase, but we can use any command listed here.
https://qemu-project.gitlab.io/qemu/system/monitor.html
Signed-off-by: Yutaro Hayakawa <yutaro.hayakawa@isovalent.com>
> Add an option to enable TCP-based QEMU monitor port

- action.yaml
Previously, it used to be `kind:5.10`. Now, it's `kind:5.10-main`. The image file name didn't change though.
The CI has passed with the suggested changes (+ 4.19) - https://github.com/cilium/cilium/actions/runs/3416955761/jobs/5687625286.
> GHA: adapt to the new img tagging format

- action.yaml
* set-output => $GITHUB_OUTPUT
* Bumps actions/cache vsn to avoid using save-state.
> Fix deprecation warnings

- action.yaml
The defaults are tailored to the poor man's ephemeral runners (4 (cores) + 4 (hyperthreads), and 8GB mem). 
cc @willfindlay
> action: Make CPU and mem configurable

- action.yaml
The LVH VM images are built on Azure, and their /etc/resolv.conf point to an Azure DNS resolvers. The DNS resolution works fine if running on GHA runners (=Azure VMs).
However, this falls short once running on GKE, which we do via the poor man's ephemeral GH action runners.
Fix this by allowing users to specify dns-resolver addr to be used in the VMs.
Signed-off-by: Martynas Pumputis <m@lambda.lt>
> action: Optionally set DNS resolver

- action.yaml
The newly introduced large runners support nested virtualisation \[1\].
To use the LVH action on it, we need to tweak a few things:
* Install qemu/kvm dependencies
* sudo /dev/kvm
\[1\]: https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners
Signed-off-by: Martynas Pumputis <m@lambda.lt>
> action: Add a support for large GHA runners

- action.yaml
Sometimes we want to run tests with a custom kernel image outside of our root filesystem. Little VM Helper supports this, but the action does not. Add a `kernel` param to the action to support this use case.
> action: enable configurable kernel image

- Makefile
Use `go install` to install the `lvh` binary to `$GOBIN` (`$HOME/go/bin` by default).
> make: add install target

- cmd/lvh/runner/conf.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
- pkg/runner/portforward.go
Move the port-forwarding code from cmd/lvh in pkg/runner. This allows using this code from other places (namely, the tetragon tester which is where most of the runner code comes from). We should do this for other parts of the runner so that cmd/lvh and tetragon tester can share the same code.
> runner: move port-forwarding code under pkg/

- pkg/images/image_build.go
Commit 1ffc67ca139b7b371b1abb2c292acc11d4f8144e introduced a chdir step. This caused an issue for subsequent steps because if the images directory is relative, the file locations are not valid anymore. This commit fixes this by updating the images directory for subequent steps.
> image_build: fix imagesDir after chroot

- pkg/kernels/url.go
It seems everything is in place to handle https:// git URLs. Tested using:
go run ./cmd/lvh kernels --dir _data add clone3-newtime-fix https://github.com/tklauser/linux.git#clone3-newtime-fix --fetch
> pkg/kernels: make https:// git URLs work

- README.md
* Correct `go run` commands. They need to point against the local `cmd/lvh`, otherwise the non-existent `$GOROOT/cmd/lvh` would be used.
* Add missing `run` sub commands in "Booting images" section.
* Fix some typos.
> README.md: various fixes

- action.yaml
We want to pass --kernel if $inputs.kernel is defined but we were accidentally checking for the opposite. This would cause the action to fail if kernel was undefined and not use the --kernel flag if it was.
> action: fix kernel argument

- action.yaml
The bash syntax for extraArgs seems to be wrong. i.e.:
```
extraArgs=()
echo ${extraArgs[@]} # prints nothing
echo ${extraArgs}[@] # prints [@]
```
```
extraArgs+=("--kernel" "test")
echo ${extraArgs[@]} # prints --kernel test
echo ${extraArgs}[@] # prints --kernel[@]
```
This patch fixes that issue.
> action: fix extraArgs

- .gitignore
- scripts/pull_image.sh
Example usage:
$ ./scripts/pull_image.sh quay.io/lvh-images/kind:bpf-next-main
> scripts: Add image pull helper

- action.yaml
Unfortunately, Github declined a proposal to pre-install qemu and friends into GHA runners \[1\]. So, let's try a poor man's solution instead.
\[1\]: https://github.com/actions/runner-images/issues/7541
Related https://github.com/cilium/cilium/issues/25483
Trying it out https://github.com/cilium/cilium/actions/runs/5001442860/jobs/8960138732.
> action.yaml: Add retry when fetching dependencies

- action.yaml
- cmd/lvh/runner/conf.go
- cmd/lvh/runner/runner.go
Sometimes it is useful to print the qemu command but still run it afterwards. The existing --qemu-print-cmd flag suppresses the qemu command after printing, so let's add a new --verbose flag that does the same thing but without the suppression.
> runner: add a verbose flag

- .github/workflows/example.yaml
Example workflow fails with:
time="2023-05-28T00:47:05Z" level=warning msg="stderr> BTF: .tmp_vmlinux.btf: pahole (pahole) is not available\n"
> gh/example: install pahole

- action.yaml
The current logic was always "true" which caused the lvh provisioning to fail with the error:
```
Error: unknown flag: --verbose
```
> fix condition logic to check for inputs.verbose

- action.yaml
The key used for the dependencies cache was incorrectly set for two reasons:
- ${{ steps.vars.find-lvh-cli.runner_os_id }} was always empty due the wrong reference name
- ${{ github.workflow_sha }} this is the commit SHA of the workflow that is being executed. Meaning that will be the SHA of the workflow that uses lvh and not the SHA of lvh, because lvh is a composite GH action. Thus, we will be using the md5sum of the dependencies' names and use it as part of the cache key.
> fix dependencies' cache key

- action.yaml
If the following steps run before the SSH server has initialized in the VM, the commands will fail causing test flakes. This can occur if the SSH server doesn't finish starting before we start sending connections to it.
See https://github.com/cilium/cilium/issues/26012
> Add step to wait for SSH Server

- action.yaml
We're still hitting [failures](https://github.com/cilium/cilium/actions/runs/5308852252/jobs/9608811629) in cilium/cilium due to "LVH VM Provisioning" because we're still using the default version of `0.0.3` (that doesn't include the SSH fix https://github.com/cilium/little-vm-helper/pull/75 and released in `v0.0.6`).
> action: Bump LVH default version to v0.0.6

- action.yaml
- cmd/lvh/runner/conf.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
These two commits allow for adding a watch on sshd's status during the "Wait for VM's SSH Server" step, in an attempt to help resolve the flakes reported in https://github.com/cilium/cilium/issues/26012. By adding the ability to check on sshd's status in the VM, more information can be gained in regards to what could be happening in these flakes. Additionally, searching for specific status strings in the console log file is an inexpensive way to wait for the sshd server to startup.
To test this, I created two VMs: one with just an ssh server that will successfully start, and one with an ssh server that will fail to start.
The logs for the successful VM show the following:
```
[  OK  ] Reached target network.target - Network.
Starting ssh.service - OpenBSD Secure Shell server...
Starting …
```
> Add watch on sshd status in "Wait for VM's SSH Server" step

- action.yaml
Currently, the action fails when trying to write to the console log file.
`qemu-system-x86_64: -serial file:/tmp/console.log: Could not open '/tmp/console.log': Permission denied`
e.g. https://github.com/cilium/cilium/actions/runs/5573110938/jobs/10180030621?pr=26819
This PR fixes this by setting the user root as owner of the file.
FYI @learnitall 
Fixes: #89
> action: fix ssh console log file permissions

- action.yaml
Once it's provisioned, we know that the SSH is working.
> action: Wait for SSH only when provisioning

- action.yaml
This commit refactors the action step to wait for the VM's SSH server.
* Increased SSH server wait timeout from 30s to 300s (default) (it's also the start of the LVM)
* Configurable wait conditions (#retries & timeout)
* Terminate check if log doesn't contain any SSH message after retries are exhausted
> action: optimize wait for VM's ssh server

- action.yaml
This commit fixes a nit in the "Wait for VM's SSH Server" step, where the value `1` is used as a false value and `0` is used as a true value.
> action: Fix boolean nit in wait for SSH server step

- action.yaml
Currently, the CI LVH VM images usage is broken in the action. For example, "kind-ci:5.15-20230925.121928" cannot be used due to:
cp: can't stat '/data/images/kind-ci_5.15.qcow2.zst': No such file or directory
This is because the actual image name doesn't contain "-ci". Fix this, by removing the "-ci" suffix from the image name derivation.
> action: Fix usage of CI images

- action.yaml
https://github.com/cilium/little-vm-helper-images/pull/187 resolves the issue with Azure DNS resolvers.
> action: Remove setting DNS resolver

- pkg/kernels/conf.go
- pkg/kernels/dir.go
This can be used for adding extra arguments to make, as it is used to build kernels.
For example:
```
{
"name": "4.19",
"url": "git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git?depth=1#linux-4.19.y"
"extra_make_args": [
"V=1",
"HOSTCC=gcc-10",
"CC=gcc-10"
]
}
```
> kernels: add a extra_make_args parameter

- cmd/lvh/kernels/configure.go
- cmd/lvh/kernels/kernels.go
- cmd/lvh/runner/conf.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
- pkg/kernels/conf.go
- pkg/kernels/dir.go
Includes an alternative version of https://github.com/cilium/little-vm-helper/pull/142
> support for building rhel8 kernels

- action.yaml
lvh images pull doesn't understand -d. The correct flag is --dir.
> action: fix incorrect -d flag

- action.yaml
Running the action currently fails with:
Error: failed to create directory /images: mkdir /images: permission denied
The commit which introduced lvh images pull didn't take into account that / is owned by ... root and therefore lvh won't be able to make the directory. It also seems like the name of the image path has changed, adjust that as well.
> action: more fixes for brokenness

- action.yaml
- cmd/lvh/runner/runner.go
- pkg/images/step_create_image.go
Revert "action: add root-dev input"
This reverts commit 0819d3228d30cd65b0c5c0408bfb4dd293fee2ff.
Signed-off-by: Lorenz Bauer <lmb@isovalent.com>
images: use /dev/vda as root device
Signed-off-by: Lorenz Bauer <lmb@isovalent.com>
lvh: make vda the default root device
RHEL8 kernels only boot using virtio. The other kernels we build support IDE
and virtio. Make vda the default so that we don't need to add vda / hda
support to the builder.
Signed-off-by: Lorenz Bauer <lmb@isovalent.com>
> use virtio to attach root device after all

- pkg/images/pull.go
Pull has two modes:
- No cache: Extract and decompress the target VM image from the docker
filesystem to the host filesystem. Result: One file, image.qcow.
- Cache: Same as no cache, but also copy the compressed image to the
host filesystem. Result: two files, image.qcow{,.zst}
Previously, the logic for extracting the target VM image from the docker
image with --cache enabled was to:
- Extract and decompress the target file directly from inside the docker
image filesystem to the host filesystem
- Do not seek the source Reader back to the start of the file
- Attempt (and fail) to copy the entire compressed image also to the
host filesystem, but starting from the end of the source file.
- This resulted in an EOF error because the reader wasn't reset to start
from the beginning. …
> images: Fix read past end of file for pull --cache

- .github/renovate.json5
- go.mod
Bumping this version in go.mod forces all developers to keep 100% up to
date on their tooling, by breaking their IDEs and compilation workflow 
if they are even just one patch release out of date. Inhibiting
developers' ability to contribute by forcing them to deal with local
administration outside of their typical update cycle creates an
unnecessary extra barrier to contribution.
For declaring the minimum required Go version in go.mod, we should set
it to the .0 patch release for the current target Go language level.
Release builds should rely on a separate mechanism to pull the latest
dependency.
This commit stops renovate from bumping the patch version in go.mod.
Related: https://github.com/cilium/cilium/pull/28686
> renovate: Disable patch release bumps in go.mod

- README.md
- cmd/lvh/kernels/build.go
- cmd/lvh/kernels/configure.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
- pkg/arch/arch.go
- pkg/images/conf.go
- pkg/images/step_create_image.go
- pkg/kernels/dir.go
- pkg/kernels/kernels.go
Fixes #56.
With this update, you can:
- Build kernel natively on both amd64 and arm64.
- Build kernel with cross-compilation on amd64 and arm64 to respectively arm64 and amd64.
- Build image natively on amd64 and arm64.
- Run the kernel with the image natively on amd64 and arm64.
You _cannot_ build an arm64 image on amd64 because of libguestfs tools limitations, unfortunately, `mmdebstrap` works perfectly fine with emulation but libguestfs tools rely on Qemu to start the VMs to modify the images and it's not set up for emulation.
Also, this introduces a new `bootable` field in the image conf since with this patch. For now, we can only build non-bootable images for arm64 as I haven't taken the time to investigate the bootloader part that we could use (since extlinux used here is x86_64 …
> Add native arm64 support and cross-compilation for kernels

- pkg/kernels/dir.go
The order of arguments passed seem to be wrong. Fix it.
> raw_configure: fix order of argument passing

- cmd/lvh/images/build.go
- pkg/images/build.go
This will be useful to specify specific images to build in the images.json file.
I need this for to build both `kind.qcow2` and `base.qcow2` in the little-vm-helper images CI for the vmtests to work on Tetragon arm64.
> cmd/images: transform --image into a string array

- cmd/lvh/runner/runner.go
- pkg/runner/conf.go
- pkg/runner/qemu.go
This will be better to use those functions as library functions if they are located in pkg/runner.
See https://github.com/cilium/tetragon/pull/2333.
> pkg/runner: move functions from cmd/lvh/runner to the pkg

- action.yaml
This can cause the action to fail on a runner on which the /images folder already exists.
Quick and (slightly) dirty fix for my needs to run LVH on hosted arm64 bare metal runners.
> action: add -p option mkdir images and fix cache

- action.yaml
Currently, the LVH GH action verifies the successful start of the SSH server by searching the console logoutput for the corresponding log lines.
This mechanism is very fragile and leads to cases where a successful SSH server start isn't detected properly. E.g. in cases where the logoutput by qemu is interleaved.
```
[  OK  ] Started     4.887573] e2scrub_all (319) used greatest stack depth: 12416 bytes left
1;39mssh.service - OpenBSD Secure Shell server.
```
Therefore, this commit removes the SSH server startup check completely. Leaving the check for a successful SSH connect to be the only check.
To respect the SSH server startup time, the default wait retries for the SSH connection check gets increased from 5 to 300 (the time that we potentially waited for the SSH startup in the log …
> gha: remove fragile SSH startup check

- .github/renovate.json5
This commit enables automerge for all renovate PRs.
https://docs.renovatebot.com/key-concepts/automerge/
Renovate will automatically merge the PRs if all all checks are successful.
Note: I have deliberately not distinguished between major/minor/... dependencies. IMO a failing check is indication enough that manual interaction is required.
@kkourt : in addition to this PR we have to allow renovate to bypass the branch protection rule. Only this way it's possible for renovate to merge PRs without any approvals. https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/
> renovate: enable automerge

- .github/renovate.json5
Currently, it seems that the presence of the label `renovate/stop-updating` github label prevents renovate from automatically merging the PRs. It only ever worked when removing the label manually.
Therefore, this commit changes the renovate configuration to not add the label when opening a pull request.
Example: https://github.com/cilium/little-vm-helper/pull/245
> renovate: don't add stop-updating label

- action.yaml
An image name that contains multiple dashes breaks because sed greedily matches on the initial `.*` pattern. To fix this, change the initial `.*` to `[^-]` so that it matches until we encounter the first dash character.
> action: fix image derive step with multiple dashes

- cmd/lvh/images/pull.go
- cmd/lvh/runner/runner.go
- pkg/arch/arch.go
- pkg/images/pull.go
- pkg/images/step_create_image.go
- pkg/kernels/dir.go
- pkg/runner/conf.go
- pkg/runner/qemu.go
After this PR, we can do:
```shell
lvh images pull quay.io/lvh-images/kind@sha256:eaa587681844b157a595afb23c1fdcc60f3e8e9a3404a8bd1c826089dc1a89da --platform linux/arm64
lvh kernel pull 5.15-main --platform linux/arm64
lvh run --qemu-arch arm64  --image _data/images/kind_5.10.qcow2 --kernel 5.15-main/boot/vmlinuz-5.15.164
```
To boot an ARM vm on x86. It would be nice to have an `images pull` that works like `kernel pull`, but this is left as a followup.
> updates to work with arm64 on x86

- action.yaml
I noticed in cilium we're not setting cpu/mem on this step: https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-runtime.yaml#L379-L395 and it's using the default of 8CPUs and 6G memory, but the runner is a 4 core machine with 16GB of memory. Since runners can vary, let's try to pick a reasonable default instead of arbitrary defaults, when the cpu/memory aren't specified.
> action.yaml: Determine default memory/cpu based on host cpu/memory when unspecified

- action.yaml
Push out a new `action.yaml` that has https://github.com/cilium/little-vm-helper/pull/353.
> Prepare for v0.0.20 release

- action.yaml
The regex that chops an image version into its name and version assumes there is only one hyphen and that separate the name from the version. The "bpf-next" images break this assumption. This commit changes the regex to handle hyphens in the image name.
> Action: Handle hyphen in image version

- action.yaml
Pick up https://github.com/cilium/little-vm-helper/pull/364.
> Prepare for v0.0.23 release

- pkg/images/build_test.go
- pkg/kernels/kernels_test.go
Starting with Go 1.24 we'll see the following errors on `go test`:
```
go test -cover ./...
github.com/cilium/little-vm-helper/cmd/lvh		coverage: 0.0% of statements
github.com/cilium/little-vm-helper/cmd/lvh/images		coverage: 0.0% of statements
github.com/cilium/little-vm-helper/cmd/lvh/kernels		coverage: 0.0% of statements
github.com/cilium/little-vm-helper/cmd/lvh/runner		coverage: 0.0% of statements
github.com/cilium/little-vm-helper/pkg/arch		coverage: 0.0% of statements
Error: pkg/images/build_test.go:21:10: non-constant format string in call to (*testing.common).Logf FAIL	github.com/cilium/little-vm-helper/pkg/images [build failed] Error: pkg/kernels/kernels_test.go:20:10: non-constant format string in call to (*testing.common).Logf FAIL …
```
> Fix Go 1.24 non-constant format string errors

- action.yaml
Action was broken when installing LVH manually, with go install for example, not using the action self install mechanism which installs in /bin/lvh because of hardcoded absolute binary path.
> action: use PATH to find lvh binary
