cilium/little-vm-helper

- cmd/lvh/main.go
Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>
> lvh: dont execute usage on error

- cmd/lvh/runner/conf.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
To debug VMs when SSH is not available:
telnet localhost $SERIAL_PORT
Passwordless user - "root".
> runner: Add serial-port

- cmd/lvh/runner/conf.go
- cmd/lvh/runner/qemu.go
- cmd/lvh/runner/runner.go
We need to give more CPU to the 4.19 and 5.4 instances.
> Add --cpu and --mem

- action.yaml
Migrating from https://github.com/cilium/little-vm-helper-action.
> Add GH action for running LVH VMs

- cmd/lvh/runner/qemu.go
- pkg/images/step_create_image.go
See commits.
Fixes: #17
Fixes: #9
> support resize for derived images

- action.yaml
> action: DNS and set -e

- action.yaml
Support selection of CPU kind and default to host CPU.
Signed-off-by: William Findlay <will@isovalent.com>
> action: support selection of cpu-kind

- action.yaml
Signed-off-by: Martynas Pumputis <m@lambda.lt>
> action: Bump LVH default vsn to v0.0.3

- action.yaml
Small note to reviewers I had to change `qemu-kvm` to `qemu-system-x86` because `qemu-kvm` doesn't seem to exist.
> Optimize provisioning time

- README.md
> fix: Fix tetragon link inside the README.md

- action.yaml
It's going to be used for exposing K8s clusters.
> action: Add additional port-forward

- action.yaml
Allow setting the new root-dev flag via the GH action.
> action: add root-dev input

- .github/renovate.json5
- RELEASE.md
- action.yaml
In particular, I'd like to make sure the default version in action.yaml gets updated before pushing the release tag so that the default version matches the action version. Right now the default version is always one version behind, which is mildly inconvenient.
Sorry for all the whitespace changes, it should be a one time thing for using yq to update action.yaml.
> Add RELEASE.md

- pkg/images/pull.go
Following up from feedback on https://github.com/cilium/little-vm-helper/pull/152, which was accelerated in order to unblock other efforts.
> Minor improvements to images pull code

- .github/workflows/quay.yaml
- Dockerfile
- Makefile
Never used ko but tested locally and this seems to work!
> Add little vm helper arm64 builds

- action.yaml
This is going to be used to expose dockerd.
> action: Allow setting multiple port fwds

- .github/renovate.json5
The action.yaml contains a reference to actions/cache, make sure that it gets updated.
> renovate: manage action.yaml

- action.yaml
The saga continues. Add a missing closing bracket.
> action: fix up image-name regex

- action.yaml
Detect LVH CLI even if installed in another location.
> ci: gh action improvement

- action.yaml
See commit msgs. The changes in action - https://github.com/cilium/pwru/actions/runs/15846789071/job/44671053558?pr=541.
> action.yaml: Add support for VM arch and kernel version

- action.yaml
> action.yaml: Bunch of changes and fixes
